---
# File: roles/hostmaster/tasks/main.yml
- name: Cache clear
  command: /bin/drush cache-clear drush
  become: yes
  become_user: aegir
- name: Create symlink for apache config
  file: path=/etc/httpd/conf.d/aegir.conf src=/var/aegir/config/apache.conf state=link force=yes
- name: Create sudoers config
  copy: dest=/etc/sudoers.d/aegir src=aegir_sudoers mode=0400
- debug: var=hostmasterinstall.stdout_lines
- name: Register aegir server with this client (register its public_key)
  # TODO: Replace this hardcoded URL with the user submitted IP address {{ aegir_server_ip }}(once the aegir server config allows it)
  get_url:
    url: http://aigersac76.westeurope.cloudapp.azure.com/public_key/id_rsa.pub
    dest: {{ aegir_home }}/.ssh/authorized_keys
  file: path={{ aegir_home }}/.ssh/authorized_keys owner={{ aegir_user }} group={{ aegir_user }}